### ISSUE TITLE
Create manifests to deploy preflight agent

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/preflight#127]
In order to help users install Preflight in their clusters, we should provide a guide and some manifests to do this.

**Sub-tasks:**
* [x] Create a readme explaining the installation of the agent
* [ ] Explain authorization requirements of datagathers, perhaps linking to updated dg docs for things like k8s rbac etc.
* [x] Create a deployment yaml to run the agent (1 replica)

**Acceptance Criteria:**

- [ ] There is a clear process outlined to install preflight with the k8s/pods and gke dg configured.

**Assumptions:**
- [ ] we're only worrying about k8s/pods and gke for now.
- [ ] users want to run preflight in a k8s cluster

This task relates to this [milestone ](https://github.com/jetstack/preflight-private/milestone/9)
