### ISSUE TITLE
Limit namespaces used in k8s datagatherer

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/preflight#128]
It's a request to be able to ignore pods in the kube-system namespace as these are often not under the control of the users in managed clusters.

**Sub-tasks:**
* [ ] support excluding namespacs in a k8s datagatherer config

**Acceptance Criteria:**

- [ ] I should be able to run the pods datagatherer without sending the pod data from the kube-system ns

**Assumptions:**
- [ ] this is a good first port of call, and label selectors and other more advanced filters are not needed at this time.

This task relates to this [milestone](https://github.com/jetstack/preflight-private/milestone/9)

**Comment by wwwil** [comment]
In terms of how this looks to users I imagine we'll add an `exclude-namespaces` field to the data gatherers config. For example:

```
- kind: "k8s/pods.v1"
  name: "pods"
  config:
    kubeconfig: /path/to/kube/config
  exclude-namespaces:
  - kube-system
  - some-other-namespace
```

There are a few different ways this could be implemented. Having looked at the data gatherer implementation the easiest way would be to use a `FieldSelector` when listing resources from the Kubernetes API in the `Fetch` function.

So the above config would generate the field selector `metadata.namespace!=kube-system,metadata.namespace!=some-other-namespace`. Which could be used in the `List` call like so:

```
	list, err := resourceInterface.List(metav1.ListOptions{
		FieldSelector: "metadata.namespace!=kube-system,metadata.namespace!=some-other-namespace"
	})
```

**Comment by charlieegan3** [comment]
Sounds good. Can we include `exclude-namespaces` under `config` though?

**Comment by wwwil** [comment]
> Can we include exclude-namespaces under config though?

Ah yeah, so it would be:

```
- kind: "k8s/pods.v1"
  name: "pods"
  config:
    kubeconfig: /path/to/kube/config
    exclude-namespaces:
    - kube-system
    - some-other-namespace
```

**Comment by charlieegan3** [comment]
:+1: looks good.
