### ISSUE TITLE
As an agent user, I'd like to be able to use the agent via an http proxy

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/preflight#132]
This is a user request being written up as a story.

It's common in certain companies to route all traffic via an http proxy - we should support this to allow those in such envs to use preflight.

**Assumptions:**
- we're talking `http_proxy` env var here

**Sub-tasks:**
* [ ] implement means of detecting the use of `http_proxy` in the env
* [ ] route via the configured proxy if it's working (e.g. if it can reach jetstack.io?)
* [ ] if the proxy is not working, crash the agent with an error

**Acceptance Criteria:**

Acceptance Criteria is a set of test scenarios specific to this particular issue. It should capture functional and non-functional requirements.

- [ ] it's possible to send data from dgs to an external backend via an http proxy

**Comment by charlieegan3** [comment]
We've tested this just now, go's https stack is already respecting the http_proxy env var being set so there should be no action needed here. Going to close.
