### ISSUE TITLE
As a user I'd like the installation of the agent to be simpler

### ISSUE THREAD

**Issue by wwwil** [jetstack/preflight#137]
Currently there are instructions on how to deploy the Preflight agent to a cluster in the `README.md`. These include inline Kubernetes manifests which users can copy, edit, and deploy.

Ideally the deployment process should be even easier and more automated. This should improve the user experience, make it less likely that mistakes are introduced while copying manifests, and make casual users more likely to deploy the agent and try Preflight.

The only part of the deployment that user must edit is the agent configuration. Most of this configuration can have sensible defaults, except the user token. This means it should all be achievable with a few commands, which user can copy from the `README.md` and run. We probably can't quite have 'one click' installation but can reduce the required steps to a few commands for a minimal deployment.

**Ideas**

- The most minimal option would be for users to just **curl** a file with several Kubernetes manifests, edit the config or use `sed` to inject a token value from an environment variable, and `kubectl apply` the file.

- A tidier version of this would be to use **Kustomize** for deployment. Users could fetch a default config file and edit as required. Kustomize Secret/ConfigMap generation would then get this into the cluster, inject values using parches, and deploy the other default manifests. Users can make their own overlays to modify the rest of the deployment.
 
- Another option is a **Helm** chart. This seems overkill but is how a lot of people expect to install applications into their cluster so is worth considering.

- Manifests could be **generated by the backend**, so when a user signs up and a token is generated a set of manifests is also generated which they can just download and apply, or apply directly from an endpoint we provide.

**Acceptance Criteria:**

Acceptance Criteria is a set of test scenarios specific to this particular issue. It should capture functional and non-functional requirements.

- [ ] There is a minimal deployment process
- [ ] The deployment process has automated testing

**Risks:**
- Poor deployment automation could make the process more painful for users
  - This can be mitigated by ensuring the deployment process is tested
- Obfuscating the deployment manifests could put users off as they're not sure what they're putting in their cluster
  - This can be mitigated by ensuring that manifests are still visible in the repo and are well documented
- Overcomplicating the deployment process can make it harder for developers to maintain
  - This requires us to agree a balance of automation and maintainability. 

**Assumptions:**
- Users want easier deployment
- Users might make mistakes copying manifests
- Casual users will be put off by having to copy and edit multiple YAML files.

**Dependencies:** 
- This will introduce a dependency whatever process we use to test the deployment automation
  - For example we may introduce kind as a dependency for testing
- This may also introduce a deployment tool as a dependency
  - For example Kustomize or Helm

**Sub-tasks:**
- [ ] Agree a deployment approach
- [ ] Implement the deployment approach
- [ ] Implement testing for the deployment
- [ ] Get a user to try the deployment and give feedback

**Comment by wwwil** [comment]
This may have been covered by https://github.com/jetstack/preflight-platform/issues/304

**Comment by charlieegan3** [comment]
I have a feeling that this is mostly done - is there work you still want to do as part of this?

**Comment by charlieegan3** [comment]
I'm closing this as we have a private issue to track improvements to this in the backend (https://github.com/jetstack/preflight-platform/issues/315)
