### ISSUE TITLE
[agent] Implement minimal config file loading for agent

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/preflight#86]
**Sub-tasks**
* [ ] implement a means of loading config - much the same as preflight core
* [ ] configure schedule variable
* [ ] configure endpoint variable
* [ ] configure identity token variable
* [ ] configure loaded data gather variables

This is just to load the vars from the file - nothing else.

Users of the agent need this to be able to control how the agents works when its running in their clusters. If we one day have a generated yaml, this might form the content of a configmap to be loaded into the running agent.

**Acceptance Criteria:**

- [ ] I can run the agent with different config
- [ ] for now, the agent just prints the config and exits

---
Internal: Created from: https://github.com/jetstack/preflight-private/issues/260 Needs: https://github.com/jetstack/preflight-private/issues/263 Enables: https://github.com/jetstack/preflight-private/issues/265
