### ISSUE TITLE
[agent] Have agent run data gathers in its config

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/preflight#90]
Users of the agent need to the agent to collect data, this should be configured based on the config file contents and work much the same as it does in preflight core

**Sub-tasks**
* [ ] use preflight-core implementation to build similar data gather functionality in the agent
* [ ] run the data gatherers configured in the config file

**Acceptance Criteria:**

- [ ] for now, the agent prints the gathered data to the console in a json format.
- [ ] only data gatherers in the config are run

--- 
Internal: Created from: https://github.com/jetstack/preflight-private/issues/260 Needs: https://github.com/jetstack/preflight-private/issues/264

**Comment by charlieegan3** [comment]
The PR for this https://github.com/jetstack/preflight/pull/95 is blocked until we get the new datagatherer config in from https://github.com/jetstack/preflight/pull/82, part of https://github.com/jetstack/preflight/issues/64.

We might need to spilt that part from the other changes to allow this to get in faster.

**Comment by j-fuentes** [comment]
I have continued with #95, which is now waiting for review.

**Comment by j-fuentes** [comment]
Clicked the wrong button :) and closed the issue by accident.
