### ISSUE TITLE
[agent] Implement data upload from agent 

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/preflight#91]
Agents are not able to evaluate packages, only gather data. They need to be able to upload to a backend.

~Needs: https://github.com/jetstack/preflight-private/issues/265~ (or it can upload can upload an empty body for now?)

Enables: https://github.com/jetstack/preflight-private/issues/267

**Sub-tasks**
* [ ] implement an agent command that gathers data and posts it to an endpoint on a given path
* [ ] configure the endpoint and path in the config file

**Acceptance Criteria:**

- [ ] there is an agent command I can run that gathers data and uploads it to the supplied endpoint

https://webhook.site can be used to test that the data is sent correctly.

---
Internal: Created from: https://github.com/jetstack/preflight-private/issues/260

**Comment by j-fuentes** [comment]
I am writing the API definition.

**Comment by charlieegan3** [comment]
Removed #265 as a requirement
